# Generated by Django 4.2.5 on 2023-10-14 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aspirante', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aspirante',
            name='imagen',
            field=models.ImageField(upload_to='aspirante'),
        ),
    ]
