# Generated by Django 4.2.5 on 2023-10-17 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asignaciones', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lineaasignacion',
            old_name='asignacion_id',
            new_name='asignacion',
        ),
        migrations.RenameField(
            model_name='lineaasignacion',
            old_name='curso_id',
            new_name='curso',
        ),
    ]
